[package]
name = "exchange-matching"
version.workspace = true
edition.workspace = true

[dependencies]
exchange-oms = { path = "../oms" }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
ordered-float = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros"] }
